---
- hosts: CSR-Laptop 

  gather_facts: false
  connection: local 

  tasks: 
   - name: Configure OSFP 100 and put all interfaces into Area 0 
     ios_config:
       lines: 
         - network 10.0.0.0 0.0.0.255 area 0
       parents: router ospf 100          

   - name: SAVE CONFIG 
     ios_command:
       commands:
         - write memory

   - name: Verify OSPF interface is Active
     ios_command:
       commands: 
         - sh run | sec router ospf 

      
